# Generated by Django 6.0.3 on 2026-03-24 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_name', models.CharField(max_length=255, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('transcription_text', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('duration', models.FloatField(default=0.0)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('start', models.FloatField(blank=True, null=True)),
                ('end', models.FloatField(blank=True, null=True)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='uibase.audioupload')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClusterSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='uibase.categorycluster')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='uibase.transcriptsegment')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('upload', 'position'), name='unique_segment_position_per_upload'),
        ),
        migrations.AddConstraint(
            model_name='clustersegment',
            constraint=models.UniqueConstraint(fields=('cluster', 'segment'), name='unique_segment_per_cluster'),
        ),
    ]
