# Generated by Django 6.0.3 on 2026-03-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uibase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycluster',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='categorycluster',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorycluster',
            name='summary_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='categorycluster',
            name='tools_needed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
