# Generated by Django 6.0.3 on 2026-03-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uibase', '0002_categorycluster_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycluster',
            name='tools_needed',
        ),
    ]
