# Generated by Django 6.0.3 on 2026-03-25 11:59

from django.db import migrations, models


def backfill_machine_taxonomy(apps, schema_editor):
    AudioUpload = apps.get_model("uibase", "AudioUpload")
    for upload in AudioUpload.objects.all().iterator():
        machine_name = (upload.machine_name or "").strip() or (upload.category or "").strip()
        machine_type = (upload.machine_type or "").strip() or "Unassigned"
        changed = False

        if upload.machine_name != machine_name:
            upload.machine_name = machine_name
            changed = True
        if upload.machine_type != machine_type:
            upload.machine_type = machine_type
            changed = True
        if changed:
            upload.save(update_fields=["machine_name", "machine_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('uibase', '0003_remove_categorycluster_tools_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioupload',
            name='extra_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='hierarchy_path',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='machine_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audioupload',
            name='machine_type',
            field=models.CharField(db_index=True, default='Unassigned', max_length=255),
        ),
        migrations.RunPython(backfill_machine_taxonomy, migrations.RunPython.noop),
    ]
