# Generated by Django 6.0.3 on 2026-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uibase', '0004_audioupload_extra_tags_audioupload_hierarchy_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycluster',
            name='needs_resummary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorycluster',
            name='stale_deleted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorycluster',
            name='stale_deleted_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
