# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


def backfill_subcategory_paths(apps, schema_editor):
    AudioUpload = apps.get_model("uibase", "AudioUpload")
    for upload in AudioUpload.objects.all().iterator():
        current_paths = upload.subcategory_paths if isinstance(upload.subcategory_paths, list) else []
        if current_paths:
            continue

        hierarchy = upload.hierarchy_path if isinstance(upload.hierarchy_path, list) else []
        cleaned = [str(value or "").strip() for value in hierarchy if str(value or "").strip()]
        if not cleaned:
            continue

        upload.subcategory_paths = [cleaned]
        upload.save(update_fields=["subcategory_paths"])


class Migration(migrations.Migration):

    dependencies = [
        ("uibase", "0005_categorycluster_needs_resummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioupload",
            name="subcategory_paths",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_subcategory_paths, migrations.RunPython.noop),
    ]
